export const SHIPMENT_STATUSES = {
  CREATED: 'created',
  OPTIMIZED: 'optimized',
  DRIVER_ASSIGNED: 'driver_assigned',
  IN_TRANSIT: 'in_transit',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
} as const;

export type ShipmentStatus = typeof SHIPMENT_STATUSES[keyof typeof SHIPMENT_STATUSES];

// The explicit allowed transitions for the Finite State Machine
export const ALLOWED_TRANSITIONS: Record<ShipmentStatus, ShipmentStatus[]> = {
  [SHIPMENT_STATUSES.CREATED]: [SHIPMENT_STATUSES.OPTIMIZED, SHIPMENT_STATUSES.CANCELLED],
  [SHIPMENT_STATUSES.OPTIMIZED]: [SHIPMENT_STATUSES.DRIVER_ASSIGNED, SHIPMENT_STATUSES.CANCELLED],
  [SHIPMENT_STATUSES.DRIVER_ASSIGNED]: [SHIPMENT_STATUSES.IN_TRANSIT, SHIPMENT_STATUSES.CANCELLED],
  [SHIPMENT_STATUSES.IN_TRANSIT]: [SHIPMENT_STATUSES.DELIVERED],
  [SHIPMENT_STATUSES.DELIVERED]: [], // Terminal State
  [SHIPMENT_STATUSES.CANCELLED]: [], // Terminal State
};
